const String awbCreated = 'AWB Created';
const String pickedUp = 'Picked Up';
const String arrivedInStation = 'Arrived in Station';
const String heldInStation = 'Held in Station';
const String departFromStation = 'Depart from Station';
const String arrivedInHub = 'Arrived in Hub';
const String departFromHub = 'Depart from Hub';
const String outForDelivery = 'Out for Delivery';
const String delivered = 'Delivered';